version: 2

jobs:
  plan-apply:
    working_directory: ~/project/
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - working_directory: ./terraform/
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply -var-file variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy -var-file variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply:
          context: arch-aws
      - hold-apply:
          context: arch-aws
          type: approval
          requires:
            - plan-apply
      - apply:
          context: arch-aws
          requires:
            - hold-apply
      - plan-destroy:
          context: arch-aws
          requires:
            - apply
      - hold-destroy:
          context: arch-aws
          type: approval
          requires:
            - plan-destroy
      - destroy:
          context: arch-aws
          requires:
            - hold-destroy
